apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadzzwh4878-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadzzwh4878-tenant-component
    app.kubernetes.io/part-of: loadzzwh4878-tenant-app
  name: loadzzwh4878-tenant-component
  namespace: loadzzwh4878-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadzzwh4878-tenant-component
    weight: null
status: {}
